### ISSUE TITLE
struct declarations create a type?

### ISSUE THREAD

**Issue by russel** [jacob-carlborg/dstep#189] opened 2018-03-19 19:23 UTC
Simplifying, I have two modules a.d and b.d that result from a DStep run. a.d has a struct definition, for example:
```d
struct X {
…
}
```
and in b.d there is:
```d
struct X;
```
This seems to create two different types: a.X and b.X. I find I have to remove the declaration in b.d and add an import statement to get the types correct.

Is this expected?

**Comment by ciechowoj** [comment] 2018-03-19 19:52
Yes, as dstep currently translates the modules separately. But this is defect obviously.

**Comment by mihails-strasuns-sociomantic** [comment] 2018-03-19 21:48
See also https://github.com/jacob-carlborg/dstep/issues/101 (essentially duplicate)

**Comment by russel** [comment] 2018-03-20 09:31
Curses, libdvbv5 has a plethora of `struct X;` declarations all over the place. I'll comment them all out and add an appropriate import for each symbol `X`. Sad, but I understand given the current state of DStep.

**Comment by jacob-carlborg** [comment] 2018-03-20 20:29
DStep has a `--skip` flag to skip generate bindings for the specified symbol.

**Comment by russel** [comment] 2018-03-21 16:36
I can't think how to use it effectively: the problem is to know which file not to use this option with. I shall cogitate further.

**Comment by jacob-carlborg** [comment] 2018-03-21 16:45
Right, I guess you would need to explicitly figure that out and the invoke DStep with different flags for different files.

**Comment by russel** [comment] 2018-03-21 18:17
Options are to find the problem and then amend the script to cope (the sensible way) or hack it manually afterwards (what I have just done). I will retrofit the script using the data, now that I have it!

**Comment by russel** [comment] 2018-03-21 18:19
I wonder if it is time to close this issue, given that #101 exists.

**Comment by jacob-carlborg** [comment] 2018-03-21 20:04
Closing as duplicate of https://github.com/jacob-carlborg/dstep/issues/101.

**Closed by jacob-carlborg** 2018-03-21 20:04 UTC
