### ISSUE TITLE
assert for struct with unions in master

### ISSUE THREAD

**Issue by pinver** [jacob-carlborg/dstep#132] opened 2017-05-19 14:01 UTC
Converting an header with struct containing a union:

```
typedef struct s_t
{
    union
    {
        float float_;
        int int_
    } value;
} sst_t;
```

```
dstep: an unknown error occurred: core.exception.AssertError@dstep/translator/Type.d(518): Unhandled type kind cast(CXTypeKind)119
----------------
4   dstep                               0x0000000109646a16 _d_assert_msg + 142
5   dstep                               0x000000010963a136 immutable(char)[] dstep.translator.Type.translateType(dstep.translator.Context.Context, clang.c.Index.CXTypeKind, bool) + 778
6   dstep                               0x0000000109638b12 immutable(char)[] dstep.translator.Type.translateType(dstep.translator.Context.Context, clang.Cursor.Cursor, clang.Type.Type, bool, bool) + 1230
7   dstep                               0x000000010963805b void dstep.translator.Translator.translateVariable(dstep.translator.Output.Output, dstep.translator.Context.Context, clang.Cursor.Cursor, immutable(char)[]) + 119
8   dstep                               0x0000000109635943 D5dstep10translator6Record18translateRecordDefFC5dstep10translator6Output6OutputC5dstep10translator7Context7ContextS5clang6Cursor6CursorbZ9__lambda5MFZ14__foreachbody1MFKS5clang6Cursor6CursorKS5clang6Cursor6CursorZi + 511
9   dstep                               0x00000001095fcb6d D5clang7Visitor18DeclarationVisitor7opApplyMFDFKS5clang6Cursor6CursorKS5clang6Cursor6CursorZiZ14__foreachbody2MFKS5clang6Cursor6CursorKS5clang6Cursor6CursorZi + 97
10  dstep                               0x00000001095fc2bc extern (C) clang.c.Index.CXChildVisitResult clang.Visitor.Visitor.visitorFunction(clang.c.Index.CXCursor, clang.c.Index.CXCursor, void*) + 80
11  libclang.dylib                      0x0000000109b6dc53 _ZN5clang8cxcursor13CursorVisitor5VisitE8CXCursorb + 305
12  libclang.dylib                      0x0000000109b6f7a4 _ZN5clang8cxcursor13CursorVisitor23handleDeclForVisitationEPKNS_4DeclE + 302
13  libclang.dylib                      0x0000000109b6f849 _ZN5clang8cxcursor13CursorVisitor16VisitDeclContextEPNS_11DeclContextE + 103
14  libclang.dylib                      0x0000000109b6f37e _ZN5clang11declvisitor4BaseINS0_8make_ptrENS_8cxcursor13CursorVisitorEbE5VisitEPNS_4DeclE + 112
15  libclang.dylib                      0x0000000109b6e51d _ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor + 405
16  libclang.dylib                      0x0000000109b780bd clang_visitChildren + 259
17  dstep                               0x00000001095fc164 int clang.Visitor.Visitor.opApply(int delegate(ref clang.Cursor.Cursor, ref clang.Cursor.Cursor)) + 144
18  dstep                               0x00000001095fcae6 int clang.Visitor.DeclarationVisitor.opApply(int delegate(ref clang.Cursor.Cursor, ref clang.Cursor.Cursor)) + 106
19  dstep                               0x0000000109635736 void dstep.translator.Record.translateRecordDef(dstep.translator.Output.Output, dstep.translator.Context.Context, clang.Cursor.Cursor, bool).__lambda5() + 90
20  dstep                               0x000000010962df7e void dstep.translator.Output.Output.Indent.opIn(void delegate()) + 90
21  dstep                               0x0000000109635694 void dstep.translator.Record.translateRecordDef(dstep.translator.Output.Output, dstep.translator.Context.Context, clang.Cursor.Cursor, bool) + 560
22  dstep                               0x0000000109635e30 void dstep.translator.Record.translateRecord(dstep.translator.Output.Output, dstep.translator.Context.Context, clang.Cursor.Cursor) + 148
23  dstep                               0x000000010963686c void dstep.translator.Translator.Translator.translate(dstep.translator.Output.Output, clang.Cursor.Cursor, clang.Cursor.Cursor) + 760
24  dstep                               0x00000001096364e8 void dstep.translator.Translator.Translator.translateInGlobalScope(dstep.translator.Output.Output, clang.Cursor.Cursor, clang.Cursor.Cursor) + 124
25  dstep                               0x0000000109636337 D5dstep10translator10Translator10Translator16translateCursorsMFZ14__foreachbody1MFKS5clang6Cursor6CursorKS5clang6Cursor6CursorZi + 219
26  dstep                               0x00000001095fc925 D5clang7Visitor14InOrderVisitor7opApplyMFDFKS5clang6Cursor6CursorKS5clang6Cursor6CursorZiZ14__foreachbody3MFKS5clang6Cursor6CursorKS5clang6Cursor6CursorZi + 617
27  dstep                               0x00000001095fc2bc extern (C) clang.c.Index.CXChildVisitResult clang.Visitor.Visitor.visitorFunction(clang.c.Index.CXCursor, clang.c.Index.CXCursor, void*) + 80
28  libclang.dylib                      0x0000000109b6dc53 _ZN5clang8cxcursor13CursorVisitor5VisitE8CXCursorb + 305
29  libclang.dylib                      0x0000000109b6f7a4 _ZN5clang8cxcursor13CursorVisitor23handleDeclForVisitationEPKNS_4DeclE + 302
30  libclang.dylib                      0x0000000109b6f849 _ZN5clang8cxcursor13CursorVisitor16VisitDeclContextEPNS_11DeclContextE + 103
31  libclang.dylib                      0x0000000109b6e8cd _ZN5clang8cxcursor13CursorVisitor13VisitChildrenE8CXCursor + 1349
32  libclang.dylib                      0x0000000109b780bd clang_visitChildren + 259
33  dstep                               0x00000001095fc164 int clang.Visitor.Visitor.opApply(int delegate(ref clang.Cursor.Cursor, ref clang.Cursor.Cursor)) + 144
34  dstep                               0x00000001095fc53f int clang.Visitor.InOrderVisitor.opApply(int delegate(ref clang.Cursor.Cursor, ref clang.Cursor.Cursor)) + 467
35  dstep                               0x0000000109636156 dstep.translator.Output.Output dstep.translator.Translator.Translator.translateCursors() + 266
36  dstep                               0x00000001096363a3 immutable(char)[] dstep.translator.Translator.Translator.translateToString() + 95
37  dstep                               0x000000010963602f void dstep.translator.Translator.Translator.translate() + 115
38  dstep                               0x00000001095fedeb void dstep.driver.Application.ParseFile.startConversion() + 887
39  dstep                               0x00000001095fe94c void dstep.driver.Application.Application.startParsingFile(const(dstep.Configuration.Configuration), immutable(char)[], immutable(char)[]) + 272
40  dstep                               0x00000001095ff5a6 void std.parallelism.Task!(void dstep.driver.Application.Application.startParsingFile(const(dstep.Configuration.Configuration), immutable(char)[], immutable(char)[]), dstep.Configuration.Configuration, immutable(char)[], immutable(char)[]).Task.impl(void*) + 98
41  dstep                               0x0000000109678a3a void std.parallelism.AbstractTask.job() + 10
42  dstep                               0x0000000109678b5f void std.parallelism.TaskPool.doJob(std.parallelism.AbstractTask*) + 23
43  dstep                               0x0000000109678c1e void std.parallelism.TaskPool.doSingleTask() + 30
44  dstep                               0x000000010964898b void core.thread.Thread.run() + 43
45  dstep                               0x0000000109647e65 thread_entryPoint + 269
46  libsystem_pthread.dylib             0x00007fffd852c93a _pthread_body + 179
47  libsystem_pthread.dylib             0x00007fffd852c886 _pthread_start + 285
48  libsystem_pthread.dylib             0x00007fffd852c08c thread_start + 12
49  ???                                 0xffffffffffffffff 0x0 + 18446744073709551615
```

**Comment by jacob-carlborg** [comment] 2017-05-19 18:33
Which version of libclang are you using?

**Comment by pinver** [comment] 2017-05-19 20:07
I'm on macOS, 4.0.0_1 installed with homebrew.

**Comment by jacob-carlborg** [comment] 2017-05-20 12:25
This is a duplicate of https://github.com/jacob-carlborg/dstep/issues/98. libclang broke the API in version 3.9. DStep only officially supports 3.7 as the latest version. I'm working on adding support for later versions.

**Closed by jacob-carlborg** 2017-05-20 12:25 UTC
Labels: duplicate
